make: don't create BINDIR for flash-only

diff --git a/Makefile.include b/Makefile.include
--- a/Makefile.include
+++ b/Makefile.include
@@ -275,12 +275,6 @@ CFLAGS += -DBOARD_$(BOARDDEF)=\"$(BOARD)\" -DRIOT_BOARD=BOARD_$(BOARDDEF)
 CFLAGS += -DCPU_$(CPUDEF)=\"$(CPU)\" -DRIOT_CPU=CPU_$(CPUDEF)
 CFLAGS += -DMCU_$(MCUDEF)=\"$(MCU)\" -DRIOT_MCU=MCU_$(MCUDEF)
 
-# OSX fails to create empty archives. Provide a wrapper to catch that error.
-ifneq (0, $(shell mkdir -p $(BINDIR); $(AR) rc $(BINDIR)/empty-archive.a 2> /dev/null; \
-            echo $$?; rm -f $(BINDIR)/empty-archive.a 2>&1 > /dev/null))
-	AR := $(RIOTBASE)/dist/ar-wrapper $(AR)
-endif
-
 # Feature test default CFLAGS and LINKFLAGS for the set compiled.
 include $(RIOTMAKE)/cflags.inc.mk
 
@@ -438,6 +432,11 @@ distclean:
 # if make target != 'flash-only', add target 'all' to ensure build before flash
 ifeq (,$(filter flash-only, $(MAKECMDGOALS)))
   BUILD_BEFORE_FLASH = all
+  # OSX fails to create empty archives. Provide a wrapper to catch that error.
+  ifneq (0, $(shell mkdir -p $(BINDIR); $(AR) rc $(BINDIR)/empty-archive.a 2> /dev/null; \
+              echo $$?; rm -f $(BINDIR)/empty-archive.a 2>&1 > /dev/null))
+    AR := $(RIOTBASE)/dist/ar-wrapper $(AR)
+  endif
 endif
 
 flash: $(BUILD_BEFORE_FLASH) $(FLASHDEPS)
