include HOME in env

diff --git a/Makefile.include b/Makefile.include
--- a/Makefile.include
+++ b/Makefile.include
@@ -103,5 +103,5 @@ debug:
 buildtest:
 	@for BOARD in $$(sed -n -e 's/ifeq[^,]*,\([^)]*\))/\1/p' $(RIOTBOARD)/Makefile.base); do \
 		echo -n "Building for $${BOARD} .. "; \
-		env -i PATH=$${PATH} BOARD=$${BOARD} RIOTBASE=$${RIOTBASE} RIOTBOARD=$${RIOTBOARD} RIOTCPU=$${RIOTCPU} $(MAKE) -B clean all >/dev/null 2>&1 && echo "success" || echo "failed"  ; \
+		env -i HOME=$${HOME} PATH=$${PATH} BOARD=$${BOARD} RIOTBASE=$${RIOTBASE} RIOTBOARD=$${RIOTBOARD} RIOTCPU=$${RIOTCPU} $(MAKE) -B clean all >/dev/null 2>&1 && echo "success" || echo "failed"  ; \
 	done
